=== NASA-AMMOS/seq-json-schema/schema.json
{
  "$id": "SeqJson",
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "activate": {
      "additionalProperties": false,
      "description": "Activate object",
      "properties": {
        "args": {
          "$ref": "#/definitions/args"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "engine": {
          "type": "integer",
          "description": "Sequence target engine."
        },
        "epoch": {
          "type": "string",
          "description": "Onboard epoch to pass to the sequence for derivation of epoch-relative timetags"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/model"
          },
          "type": "array"
        },
        "sequence": {
          "type": "string",
          "description": "Onboard path and filename of sequence to be loaded."
        },
        "time": {
          "$ref": "#/definitions/time"
        },
        "type": {
          "const": "activate"
        }
      },
      "required": ["sequence", "time", "type"],
      "type": "object"
    },
    "args": {
      "description": "Array of command arguments",
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "number"
          },
          {
            "type": "boolean"
          },
          {
            "$ref": "#/definitions/symbol_argument"
          },
          {
            "$ref": "#/definitions/hex_argument"
          }
        ]
      }
    },
    "command": {
      "additionalProperties": false,
      "description": "Command object",
      "properties": {
        "args": {
          "$ref": "#/definitions/args"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/model"
          },
          "type": "array"
        },
        "stem": {
          "type": "string",
          "description": "Command stem"
        },
        "time": {
          "$ref": "#/definitions/time"
        },
        "type": {
          "const": "command"
        },
        "return_assign_to": {
          "description": "Name of a defined local variable to which the exit status of this command should be written to. For this to work, that local variable must have been defined with the 'SC_Name' property set to LCS",
          "type": "string"
        }
      },
      "required": ["stem", "args", "time", "type"],
      "type": "object"
    },
    "description": {
      "description": "Description. Can be attached to any sequence step.",
      "type": "string"
    },
    "ground_block": {
      "additionalProperties": false,
      "description": "Ground blocks",
      "properties": {
        "args": {
          "$ref": "#/definitions/args"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/model"
          },
          "type": "array"
        },
        "name": {
          "description": "Ground block name",
          "type": "string"
        },
        "time": {
          "$ref": "#/definitions/time"
        },
        "type": {
          "const": "ground_block"
        }
      },
      "required": ["name", "time", "type"],
      "type": "object"
    },
    "ground_epoch": {
      "description": "Ground epoch object",
      "properties": {
        "delta": {
          "description": "Epoch delta given as a duration, start time will be epoch+delta.",
          "type": "string"
        },
        "name": {
          "description": "Name of ground-defined epoch.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ground_event": {
      "additionalProperties": false,
      "description": "Ground events",
      "properties": {
        "args": {
          "$ref": "#/definitions/args"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/model"
          },
          "type": "array"
        },
        "name": {
          "description": "Ground event name",
          "type": "string"
        },
        "time": {
          "$ref": "#/definitions/time"
        },
        "type": {
          "const": "ground_event"
        }
      },
      "required": ["name", "time", "type"],
      "type": "object"
    },
    "load": {
      "additionalProperties": false,
      "description": "Load object",
      "properties": {
        "args": {
          "$ref": "#/definitions/args"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "engine": {
          "type": "integer",
          "description": "Sequence target engine."
        },
        "epoch": {
          "type": "string",
          "description": "Onboard epoch to pass to the sequence for derivation of epoch-relative timetags"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/model"
          },
          "type": "array"
        },
        "sequence": {
          "type": "string",
          "description": "Onboard path and filename of sequence to be loaded."
        },
        "time": {
          "$ref": "#/definitions/time"
        },
        "type": {
          "const": "load"
        }
      },
      "required": ["sequence", "time", "type"],
      "type": "object"
    },
    "metadata": {
      "description": "Flexible sequence metadata for any key-value pairs.",
      "type": "object"
    },
    "model": {
      "additionalProperties": false,
      "description": "Model object that be included with commands to set variables for modeling purposes only, usually to direct sequence execution down a particular branch during modeling.",
      "properties": {
        "offset": {
          "description": "Duration to wait after step time to trigger model change",
          "type": "string"
        },
        "value": {
          "description": "Value to set in variable.",
          "type": ["string", "number", "boolean"]
        },
        "variable": {
          "description": "Variable to be set in the model",
          "type": "string"
        }
      },
      "required": ["offset", "value", "variable"],
      "type": "object"
    },
    "request": {
      "additionalProperties": false,
      "description": "Sequence steps can be grouped into a request, which can then be shifted or adjusted altogether as part of the request.",
      "oneOf": [
        {
          "required": ["ground_epoch"]
        },
        {
          "required": ["time"]
        }
      ],
      "properties": {
        "description": {
          "$ref": "#/definitions/description"
        },
        "ground_epoch": {
          "$ref": "#/definitions/ground_epoch"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "name": {
          "description": "Request Name, used for tracking commands back to the original request after ground expansion. Must be unique.",
          "type": "string"
        },
        "steps": {
          "description": "Sequence steps that are part of this request.",
          "items": {
            "$ref": "#/definitions/step"
          },
          "minItems": 1,
          "type": "array"
        },
        "time": {
          "$ref": "#/definitions/time"
        },
        "type": {
          "const": "request"
        }
      },
      "required": ["name", "steps", "type"],
      "type": "object"
    },
    "step": {
      "oneOf": [
        {
          "$ref": "#/definitions/activate"
        },
        {
          "$ref": "#/definitions/command"
        },
        {
          "$ref": "#/definitions/ground_block"
        },
        {
          "$ref": "#/definitions/ground_event"
        },
        {
          "$ref": "#/definitions/load"
        }
      ]
    },
    "immediate_command": {
      "additionalProperties": false,
      "description": "Object representing a single Immediate Command",
      "properties": {
        "args": {
          "$ref": "#/definitions/args"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "stem": {
          "type": "string",
          "description": "Command stem"
        }
      },
      "required": ["stem", "args"],
      "type": "object"
    },
    "hardware_command": {
      "additionalProperties": false,
      "description": "Object representing a single Hardware Command",
      "properties": {
        "description": {
          "$ref": "#/definitions/description"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "stem": {
          "type": "string",
          "description": "Command stem"
        }
      },
      "required": ["stem"],
      "type": "object"
    },
    "time": {
      "additionalProperties": false,
      "description": "Time object",
      "properties": {
        "tag": {
          "description": "Relative or absolute time. Required for ABSOLUTE, COMMAND_RELATIVE, and EPOCH_RELATIVE time tags but not COMMAND_COMPLETE.",
          "type": "string"
        },
        "type": {
          "description": "Allowed time types: ABSOLUTE, COMMAND_RELATIVE, EPOCH_RELATIVE, or COMMAND_COMPLETE.",
          "enum": ["ABSOLUTE", "COMMAND_RELATIVE", "EPOCH_RELATIVE", "COMMAND_COMPLETE"],
          "type": "string"
        }
      },
      "required": ["type"],
      "type": "object"
    },
    "variable_range": {
      "additionalProperties": false,
      "description": "A range of allowable variable values between a defined min and max, inclusive. min and max must be numbers",
      "properties": {
        "min": {
          "description": "Minimum value of the variable, inclusive",
          "type": "number"
        },
        "max": {
          "description": "Maximum value of the variable, inclusive",
          "type": "number"
        }
      },
      "required": ["min", "max"],
      "type": "object"
    },
    "symbol_argument": {
      "additionalProperties": false,
      "description": "A step argument referencing a local or global variable, or some other symbolic name known to downstream modeling software (such as CONDITION in SEQGEN)",
      "properties": {
        "symbol": {
          "description": "The symbolic name being referenced.",
          "type": "string"
        }
      },
      "required": ["symbol"],
      "type": "object"
    },
    "hex_argument": {
      "additionalProperties": false,
      "description": "A step argument containing an unsigned integer in hexadecimal format.",
      "properties": {
        "hex": {
          "description": "The hexadecimal integer, as a string prefixed with 0x. Digits A-F must be uppercase.",
          "pattern": "^0x([0-9A-F])+$",
          "type": "string"
        }
      },
      "required": ["hex"],
      "type": "object"
    },
    "variable_declaration": {
      "allOf": [
        {
          "description": "Variable (local or parameter) declarations.",
          "additionalProperties": false,
          "properties": {
            "type": {
              "description": "Variable type. Allowed types: FLOAT, INT, STRING, UINT, ENUM.",
              "enum": ["FLOAT", "INT", "STRING", "UINT", "ENUM"],
              "type": "string"
            },
            "name": {
              "description": "User-friendly variable names that will be mapped to FSW variable names. Must begin with a letter and contain only letters, numbers, and underscores.",
              "pattern": "^[A-Za-z][A-Za-z_0-9]*$",
              "type": "string"
            },
            "enum_name": {
              "description": "For enumerated type variables, the name of the corresponding FSW-defined ENUM.",
              "pattern": "^[A-Za-z][A-Za-z_0-9]*$",
              "type": "string"
            },
            "allowable_values": {
              "description": "A list of allowable values for this variable.",
              "type": "array"
            },
            "allowable_ranges": {
              "description": "One or more allowable ranges of values, for FLOAT, INT, or UINT variable types.",
              "type": "array",
              "items": {
                "$ref": "#/definitions/variable_range"
              }
            },
            "sc_name": {
              "description": "The FSW-specified name for this variable that should be used in the translated sequence, in case this must be specified. Used for variables which are specially-handled onboard such as LCS (Last Command Status)",
              "type": "string"
            }
          },
          "required": ["type", "name"],
          "type": "object"
        },
        {
          "$comment": "This if/then/else block causes 'enum_name' to be a required property if the type is ENUM, and disallows it otherwise.",
          "if": {
            "properties": {
              "type": {
                "const": "ENUM"
              }
            }
          },
          "then": {
            "required": ["enum_name"]
          },
          "else": {
            "properties": {
              "enum_name": false
            }
          }
        },
        {
          "$comment": "This if/then/else block causes 'allowable_values' to require a number as its array item type if the variable type is FLOAT, UINT, or INT. If it is STRING or ENUM, it causes 'allowable_values' to require a string and disallows 'allowable_ranges'.",
          "if": {
            "properties": {
              "type": {
                "oneOf": [
                  {
                    "const": "FLOAT"
                  },
                  {
                    "const": "UINT"
                  },
                  {
                    "const": "INT"
                  }
                ]
              }
            }
          },
          "then": {
            "properties": {
              "allowable_values": {
                "items": {
                  "type": "number"
                }
              }
            }
          },
          "else": {
            "properties": {
              "allowable_values": {
                "items": {
                  "type": "string"
                }
              },
              "allowable_ranges": false
            }
          }
        }
      ]
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier",
      "type": "string"
    },
    "locals": {
      "description": "Local variable declarations.",
      "items": {
        "$ref": "#/definitions/variable_declaration"
      },
      "minItems": 1,
      "type": "array"
    },
    "metadata": {
      "$ref": "#/definitions/metadata"
    },
    "parameters": {
      "description": "Parameter variable declarations.",
      "items": {
        "$ref": "#/definitions/variable_declaration"
      },
      "minItems": 1,
      "type": "array"
    },
    "requests": {
      "description": "Commands groups into requests",
      "items": {
        "$ref": "#/definitions/request"
      },
      "type": "array"
    },
    "steps": {
      "description": "Sequence steps",
      "items": {
        "$ref": "#/definitions/step"
      },
      "type": "array"
    },
    "immediate_commands": {
      "description": "Immediate commands which are interpreted by FSW and not part of any sequence.",
      "items": {
        "$ref": "#/definitions/immediate_command"
      },
      "type": "array"
    },
    "hardware_commands": {
      "description": "Hardware commands which are not interpreted by FSW and not part of any sequence.",
      "items": {
        "$ref": "#/definitions/hardware_command"
      },
      "type": "array"
    }
  },
  "required": ["id", "metadata"],
  "type": "object"
}

=== NASA-AMMOS/seq-json-schema/test/valid-seq-json/all-possible-fields.seq.json
{
  "id": "all_possible_fields",
  "metadata": {
    "onboard_path": "/eng",
    "onboard_name": "test.mod",
    "lgo": false,
    "other_arbitrary_metadata": "test_metadata"
  },
  "locals": [
    {
      "name": "local_float_1",
      "type": "FLOAT"
    },
    {
      "name": "local_int_2",
      "type": "INT"
    },
    {
      "name": "local_string_3",
      "type": "STRING"
    },
    {
      "name": "local_uint_4",
      "type": "UINT"
    }
  ],
  "parameters": [
    {
      "name": "param_float_1",
      "type": "FLOAT"
    },
    {
      "name": "param_int_2",
      "type": "INT"
    },
    {
      "name": "param_string_3",
      "type": "STRING"
    },
    {
      "name": "param_uint_4",
      "type": "UINT"
    }
  ],
  "steps": [
    {
      "args": [30, 4.3, true, "test_string"],
      "description": "Epoch-relative activate step for test.mod into engine 2 with all possible fields.",
      "engine": 2,
      "epoch": "TEST_EPOCH",
      "models": [
        {
          "offset": "00:00:00.000",
          "variable": "model_var_float",
          "value": "1.234"
        },
        {
          "offset": "00:00:00.001",
          "variable": "model_var_int",
          "value": "-1234"
        },
        {
          "offset": "01:02:03.000",
          "variable": "model_var_string",
          "value": "Model test string"
        },
        {
          "offset": "10:00:00.000",
          "variable": "model_var_uint",
          "value": "1234"
        }
      ],
      "sequence": "d:/eng/test.mod",
      "time": { "tag": "00:00:01.000", "type": "EPOCH_RELATIVE" },
      "type": "activate"
    },
    {
      "args": [30, 4.3, false, "test_string"],
      "description": "Absolute-timed standard command step with all possible fields.",
      "models": [
        {
          "offset": "00:00:00.000",
          "variable": "model_var_float",
          "value": "1.234"
        },
        {
          "offset": "00:00:00.001",
          "variable": "model_var_int",
          "value": "-1234"
        },
        {
          "offset": "01:02:03.000",
          "variable": "model_var_string",
          "value": "Model test string"
        },
        {
          "offset": "10:00:00.000",
          "variable": "model_var_uint",
          "value": "1234"
        }
      ],
      "stem": "FAKE_COMMAND1",
      "time": { "tag": "2020-173T20:00:00.000", "type": "ABSOLUTE" },
      "type": "command",
      "metadata": {}
    },
    {
      "args": [
        "SEQSTR",
        "2019-365T00:00:00",
        "2020-025T00:00:00",
        "BOTH",
        "",
        "",
        "real_time_cmds"
      ],
      "description": "Ground activity step with required fields.",
      "models": [
        {
          "offset": "00:00:00.000",
          "variable": "model_var_float",
          "value": "1.234"
        },
        {
          "offset": "00:00:00.001",
          "variable": "model_var_int",
          "value": "-1234"
        },
        {
          "offset": "01:02:03.000",
          "variable": "model_var_string",
          "value": "Model test string"
        },
        {
          "offset": "10:00:00.000",
          "variable": "model_var_uint",
          "value": "1234"
        }
      ],
      "name": "SEQTRAN_directive",
      "time": { "tag": "00:00:01.000", "type": "COMMAND_RELATIVE" },
      "type": "ground_block",
      "metadata": { "stringfield": "stringval" }
    },
    {
      "args": [
        "/domops/data/nsyt/189/seq/satf_sct/nsy.orf.f2_seq_eng_nom_htr_off_mod.r1.satf",
        "d:/tmp/eng_nom_htr_off.mod"
      ],
      "description": "Ground event step with all possible fields.",
      "models": [
        {
          "offset": "00:00:00.000",
          "variable": "model_var_float",
          "value": "1.234"
        },
        {
          "offset": "00:00:00.001",
          "variable": "model_var_int",
          "value": "-1234"
        },
        {
          "offset": "01:02:03.000",
          "variable": "model_var_string",
          "value": "Model test string"
        },
        {
          "offset": "10:00:00.000",
          "variable": "model_var_uint",
          "value": "1234"
        }
      ],
      "name": "UPLINK_SEQUENCE_FILE",
      "time": { "type": "COMMAND_COMPLETE" },
      "type": "ground_event",
      "metadata": { "listfield": ["1", 2] }
    },
    {
      "args": [{ "symbol": "Local_Var_A" }, { "symbol": "Global_Var_B" }],
      "description": "Epoch-relative activate step for test.mod into engine 2 with all possible fields.",
      "engine": 2,
      "epoch": "TEST_EPOCH",
      "models": [
        {
          "offset": "00:00:00.000",
          "variable": "model_var_float",
          "value": "1.234"
        },
        {
          "offset": "00:00:00.001",
          "variable": "model_var_int",
          "value": "-1234"
        },
        {
          "offset": "01:02:03.000",
          "variable": "model_var_string",
          "value": "Model test string"
        },
        {
          "offset": "10:00:00.000",
          "variable": "model_var_uint",
          "value": "1234"
        }
      ],
      "sequence": "d:/eng/test.mod",
      "time": { "tag": "00:00:01.000", "type": "EPOCH_RELATIVE" },
      "type": "load"
    }
  ],
  "requests": [
    {
      "description": "Absolute-timed request object with all possible fields",
      "name": "test_request1",
      "steps": [
        {
          "stem": "FAKE_COMMAND1",
          "time": { "tag": "00:00:01.000", "type": "COMMAND_RELATIVE" },
          "type": "command",
          "args": []
        }
      ],
      "time": { "tag": "2020-173T20:00:00.000", "type": "ABSOLUTE" },
      "type": "request"
    },
    {
      "description": "Ground-epoch timed request object with all possible fields",
      "ground_epoch": { "delta": "+00:30:00", "name": "test_ground_epoch" },
      "name": "test_request1",
      "steps": [
        {
          "stem": "FAKE_COMMAND1",
          "time": { "tag": "00:00:01.000", "type": "COMMAND_RELATIVE" },
          "type": "command",
          "args": []
        }
      ],
      "type": "request"
    }
  ]
}

=== NASA-AMMOS/seq-json-schema/test/valid-seq-json/example-seq-ieee.seq.json
{
  "id": "ganymede_flyby_045_images",
  "metadata": {
    "onboard_path": "/eng",
    "onboard_name": "ganymede_flyby_045_images.seq",
    "lgo": false
  },
  "parameters": [
    { "name": "compression_algorithm", "type": "STRING" },
    { "name": "register", "type": "UINT" }
  ],
  "steps": [
    {
      "type": "command",
      "time": { "tag": "2020-173T20:00:00.000", "type": "ABSOLUTE" },
      "stem": "TURN_IMAGER_HEATER_ON",
      "args": [{ "string": "SIDE_A" }],
      "description": "Absolute-timed command to turn a heater on, with simulated telemetry change 5 minutes later.",
      "models": [{ "offset": "00:05:00", "variable": "IMAGER_A_WARMED_UP", "value": true }]
    },
    {
      "type": "activate",
      "time": { "tag": "00:10:00.000", "type": "COMMAND_RELATIVE" },
      "engine": 2,
      "sequence": "/eng/configure_imager.seq",
      "args": [{ "string": "MOSAIC" }, { "boolean": true }, { "number": 10 }],
      "description": "Relative-timed sequence activate"
    },
    {
      "type": "command",
      "time": { "type": "EPOCH_RELATIVE", "tag": "-00:00:15.54" },
      "stem": "TAKE_IMAGE",
      "args": [{ "string": "HI_RES" }],
      "description": "Epoch-relative timed command, with metadata",
      "metadata": {
        "source": "Expanded from activity TAKE_GANYMEDE_FLYBY_IMAGE_045"
      }
    },
    {
      "type": "ground_block",
      "name": "process_image_data",
      "args": [{ "string": "compression_algorithm" }, { "string": "register" }],
      "time": { "type": "COMMAND_COMPLETE" },
      "description": "Command-complete timed ground block, using parameter passing from input parameters."
    },
    {
      "type": "ground_event",
      "time": { "tag": "2020-174T04:40:00.000", "type": "ABSOLUTE" },
      "name": "SIMULATE_FILE_UPLINK",
      "args": [
        { "string": "/usr/mschaffe/ganymede_flyby_046_images.seq.json" },
        { "string": "/eng/ganymede_flyby_046_images.seq" }
      ],
      "description": "Ground event step, simulating a file uplink (not a real command)"
    }
  ]
}

=== NASA-AMMOS/seq-json-schema/test/valid-seq-json/variable-sequence.seq.json
{
  "id": "variable_sequence",
  "locals": [
    {
      "name": "STRING_LOCAL",
      "type": "STRING"
    },
    {
      "name": "UINT_LOCAL",
      "type": "UINT"
    },
    {
      "name": "INT_LOCAL",
      "type": "INT"
    },
    {
      "name": "FLOAT_LOCAL",
      "type": "FLOAT"
    },
    {
      "name": "ENUM_LOCAL",
      "type": "ENUM",
      "enum_name": "ONBOARD_ENUM_01"
    },
    {
      "name": "STRING_WITH_VALS",
      "type": "STRING",
      "allowable_values": ["ONE", "TWO", "THREE"]
    },
    {
      "name": "ENUM_WITH_VALS",
      "type": "ENUM",
      "enum_name": "ONBOARD_ENUM_02",
      "allowable_values": ["ONE", "TWO"]
    },
    {
      "name": "UINT_WITH_VALS",
      "type": "UINT",
      "allowable_values": [1, 2, 3]
    },
    {
      "name": "INT_WITH_RANGES",
      "type": "INT",
      "allowable_ranges": [
        {
          "min": 1,
          "max": 2
        },
        {
          "min": 600,
          "max": 800
        }
      ]
    },
    {
      "name": "STRING_WITH_SC_NAME",
      "type": "STRING",
      "sc_name": "LCS"
    }
  ],
  "metadata": {
    "onboard_name": "variable_sequence",
    "onboard_path": "variable_path"
  },
  "steps": [
    {
      "stem": "CMD_NOOP",
      "time": {
        "tag": "00:00:01.000",
        "type": "COMMAND_RELATIVE"
      },
      "type": "command",
      "args": []
    }
  ]
}

=== NASA-AMMOS/seq-json-schema/test/valid-seq-json/command.seq.json
{
  "id": "command",
  "metadata": {},
  "locals": [
    {
      "name": "local_float_1",
      "type": "FLOAT",
      "sc_name": "LCS"
    }
  ],
  "steps": [
    {
      "args": [{ "number": 30 }, { "number": 4.3 }, { "boolean": false }, { "string": "test_string" }],
      "description": "Absolute-timed standard command step with all possible fields.",
      "models": [
        {
          "offset": "00:00:00.000",
          "variable": "model_var_float",
          "value": "1.234"
        },
        {
          "offset": "00:00:00.001",
          "variable": "model_var_int",
          "value": "-1234"
        },
        {
          "offset": "01:02:03.000",
          "variable": "model_var_string",
          "value": "Model test string"
        },
        {
          "offset": "10:00:00.000",
          "variable": "model_var_uint",
          "value": "1234"
        }
      ],
      "stem": "FAKE_COMMAND1",
      "time": { "tag": "2020-173T20:00:00.000", "type": "ABSOLUTE" },
      "type": "command",
      "metadata": {},
      "return_assign_to": "local_float_1"
    }
  ]
}

=== NASA-AMMOS/seq-json-schema/test/valid-seq-json/steps-and-requests.seq.json
{
  "id": "steps_and_requests",
  "metadata": {
    "onboard_name": "test",
    "onboard_path": "test"
  },
  "requests": [
    {
      "description": "Absolute-timed request object with all possible fields",
      "name": "test_request1",
      "steps": [
        {
          "stem": "FAKE_COMMAND1",
          "time": {
            "tag": "00:00:01.000",
            "type": "COMMAND_RELATIVE"
          },
          "type": "command",
          "args": []
        }
      ],
      "time": {
        "tag": "2020-173T20:00:00.000",
        "type": "ABSOLUTE"
      },
      "type": "request"
    },
    {
      "description": "Ground-epoch timed request object with all possible fields",
      "ground_epoch": {
        "delta": "+00:30:00",
        "name": "test_ground_epoch"
      },
      "name": "test_request1",
      "steps": [
        {
          "stem": "FAKE_COMMAND1",
          "time": {
            "tag": "00:00:01.000",
            "type": "COMMAND_RELATIVE"
          },
          "type": "command",
          "args": []
        }
      ],
      "type": "request"
    }
  ],
  "steps": [
    {
      "args": [30, 4.3, true, "test_string"],
      "description": "Epoch-relative activate step for test.mod into engine 2 with all possible fields.",
      "engine": 2,
      "epoch": "TEST_EPOCH",
      "models": [
        {
          "offset": "00:00:00.000",
          "value": "1.234",
          "variable": "model_var_float"
        }
      ],
      "sequence": "d:/eng/test.mod",
      "time": {
        "tag": "00:00:01.000",
        "type": "EPOCH_RELATIVE"
      },
      "type": "activate"
    },
    {
      "args": [
        30,
        4.3,
        false,
        "test_string",
        {
          "symbol": "Global_Var_A"
        }
      ],
      "description": "Absolute-timed standard command step with all possible fields.",
      "models": [
        {
          "offset": "00:00:00.000",
          "value": "1.234",
          "variable": "model_var_float"
        }
      ],
      "stem": "FAKE_COMMAND1",
      "time": {
        "tag": "2020-173T20:00:00.000",
        "type": "ABSOLUTE"
      },
      "type": "command",
      "args": []
    }
  ]
}
